### ISSUE TITLE
admin 页面会出现多个教师管理

### ISSUE THREAD

**Issue by jeffytang** [jeffytang/test-online#12]
admin 页面会出现多个教师管理，应该只能出现一个

**Comment by jeffytang** [comment]
![Uploading image.png…]()

**Comment by jeffytang** [comment]
![image](https://user-images.githubusercontent.com/10086340/101320246-60813200-389e-11eb-8723-8eef3e2dc8a5.png)

**Comment by XqTang-call** [comment]
不是 bug
